INSERT INTO countries (name, slug) VALUES
('Ireland','ie'),
('United Kingdom','uk'),
('Canada','ca'),
('United States','us');

INSERT INTO locations (name, slug, country_id) VALUES
('Manchester','manchester',2),
('London','london',2),
('Birmingham','birmingham',2),
('Liverpool','liverpool',2),
('Leeds','leeds',2),
('Glasgow','glasgow',2),
('Edinburgh','edinburgh',2),
('Cardiff','cardiff',2),
('Bristol','bristol',2),
('Sheffield','sheffield',2);

INSERT INTO categories (name, slug) VALUES
('Men Seeking Women','men-seeking-women'),
('Men Seeking Men','men-seeking-men'),
('Women Seeking Men','women-seeking-men'),
('Women Seeking Women','women-seeking-women'),
('Casual Encounters','casual-encounters'),
('Serious Relationships','serious-relationships'),
('Friends & Chat','friends-chat'),
('Kinks & Fetish','kinks-fetish'),
('Swingers & Couples','swingers-couples'),
('Discreet & NSA','discreet-nsa');

INSERT INTO subcategories (category_id, name, slug) VALUES
(1,'Dating','dating'),
(1,'Casual Fun','casual-fun'),
(1,'Long Term','long-term'),
(2,'Casual','casual'),
(2,'Bears','bears'),
(2,'Twinks','twinks'),
(3,'Dating','dating'),
(3,'Casual Fun','casual-fun'),
(3,'Long Term','long-term'),
(4,'Romantic','romantic'),
(4,'Casual','casual'),
(4,'Friendship','friendship'),
(5,'One Night','one-night'),
(5,'Friends With Benefits','friends-with-benefits'),
(6,'Marriage Minded','marriage-minded'),
(6,'Long Term','long-term'),
(7,'Online Chat','online-chat'),
(7,'Penpals','penpals'),
(8,'BDSM','bdsm'),
(8,'Roleplay','roleplay'),
(9,'Couples','couples'),
(9,'Group Fun','group-fun'),
(10,'No Strings','no-strings'),
(10,'Discreet Meets','discreet-meets');

INSERT INTO users (username, email, password_hash) VALUES
('irishgeoff','irishgeoff@yahoo.com','{{PASSWORD_HASH}}');

INSERT INTO ads (user_id,title,description,category_id,subcategory_id,location_id) VALUES
(1,'Manchester — Looking for genuine connection','Easygoing, friendly, and open to meeting someone real. Coffee first, see where it goes.',1,1,1),
(1,'London — Casual meetups','No pressure, just good vibes. Discreet and respectful.',5,11,2),
(1,'Liverpool — Up for chats and drinks','Let’s grab a drink and see if we click.',7,13,4),
(1,'Leeds — Discreet meets only','Prefer privacy and maturity. No drama.',10,20,5),
(1,'Birmingham — Long term vibes','Looking for something meaningful and lasting.',6,16,3),
(1,'Glasgow — Friendly guy looking to meet','Open-minded and easygoing. Let’s chat.',1,2,6),
(1,'Edinburgh — Coffee and conversation','Love deep chats and good company.',3,7,7),
(1,'Cardiff — No strings fun','Just keeping things simple and fun.',5,11,8),
(1,'Bristol — Looking for friendship first','Let’s build something real.',7,13,9),
(1,'Sheffield — Open to new connections','Seeing who’s out there.',1,1,10),

(1,'Manchester — Weekend coffee?','Chilled guy looking for someone to grab a weekend coffee with.',1,1,1),
(1,'London — After-work drinks','Work is hectic, looking for someone to unwind with.',7,13,2),
(1,'Birmingham — Casual chats','Not rushing anything, just seeing who’s around.',5,11,3),
(1,'Liverpool — Looking for laughs','Sense of humour essential. Let’s keep it light.',7,14,4),
(1,'Leeds — Mature meets','Prefer older, confident people who know what they want.',10,20,5),
(1,'Glasgow — Exploring connections','Open to something casual or more.',1,2,6),
(1,'Edinburgh — Book lover seeking same','If you love reading, we’ll get along.',3,7,7),
(1,'Cardiff — No expectations','Let’s just vibe and see what happens.',5,11,8),
(1,'Bristol — Friendly chats','Looking for someone genuine to talk to.',7,13,9),
(1,'Sheffield — Open-minded guy','Happy to chat and meet if we click.',1,2,10),

(1,'Manchester — Gym buddy?','Looking for someone to train with and maybe more.',1,2,1),
(1,'London — Discreet fun','Respectful, clean, and private meets only.',10,20,2),
(1,'Birmingham — Long-term connection','Ready for something real.',6,16,3),
(1,'Liverpool — Drinks and banter','Let’s keep it fun and relaxed.',7,13,4),
(1,'Leeds — Coffee date?','Simple, easygoing, and friendly.',3,7,5),
(1,'Glasgow — Looking for chemistry','If we click, great. If not, no worries.',1,1,6),
(1,'Edinburgh — Walks and talks','Love exploring the city with good company.',3,7,7),
(1,'Cardiff — No strings attached','Just keeping things simple.',5,11,8),
(1,'Bristol — Friendship first','Let’s build something meaningful.',7,13,9),
(1,'Sheffield — Open to ideas','Let’s chat and see what happens.',1,2,10),

(1,'Manchester — Looking for someone chilled','No drama, no pressure.',1,1,1),
(1,'London — Casual chats','Happy to talk and meet if we vibe.',5,11,2),
(1,'Birmingham — Seeking connection','Looking for someone genuine.',6,16,3),
(1,'Liverpool — Friendly meetups','Let’s grab a drink.',7,13,4),
(1,'Leeds — Discreet only','Privacy is important.',10,20,5),
(1,'Glasgow — Open-minded','Seeing who’s around.',1,2,6),
(1,'Edinburgh — Coffee lover','Let’s chat over a latte.',3,7,7),
(1,'Cardiff — Fun times','Keeping it light.',5,11,8),
(1,'Bristol — Looking for friends','Let’s talk.',7,13,9),
(1,'Sheffield — New connections','Open to meeting.',1,1,10),

(1,'Manchester — Late night chats','Night owl looking for someone similar.',7,13,1),
(1,'London — Quick coffee?','In the area often, let’s meet.',1,1,2),
(1,'Birmingham — Looking for real talk','Honest conversations only.',6,16,3),
(1,'Liverpool — Chill vibes','Let’s keep it simple.',5,11,4),
(1,'Leeds — Mature chats','Prefer older.',10,20,5),
(1,'Glasgow — Friendly meet','Open-minded and relaxed.',1,2,6),
(1,'Edinburgh — Bookshop dates','If you love books, we’ll get along.',3,7,7),
(1,'Cardiff — No pressure','Just seeing who’s around.',5,11,8),
(1,'Bristol — Looking for good company','Friendly and easygoing.',7,13,9),
(1,'Sheffield — Open to chats','Let’s talk.',1,1,10),

(1,'Manchester — Looking for a walking buddy','Love long walks and good conversation.',1,1,1),
(1,'London — Coffee and a chat','Simple and relaxed.',7,13,2),
(1,'Birmingham — Open to meeting','Seeing who’s around.',5,11,3),
(1,'Liverpool — Friendly guy here','Let’s talk and see where it goes.',7,13,4),
(1,'Leeds — Looking for something real','Ready for a connection.',6,16,5),
(1,'Glasgow — Casual meets','Keeping it easy.',1,2,6),
(1,'Edinburgh — Looking for someone genuine','Let’s chat.',3,7,7),
(1,'Cardiff — Open-minded','Seeing what happens.',5,11,8),
(1,'Bristol — Friendly and chilled','Let’s meet.',7,13,9),
(1,'Sheffield — Looking for company','Open to ideas.',1,1,10),

(1,'Manchester — Coffee lover','Let’s grab a flat white.',1,1,1),
(1,'London — After work meet','Relaxed and friendly.',7,13,2),
(1,'Birmingham — Looking for chats','Open to meeting.',5,11,3),
(1,'Liverpool — No pressure meets','Let’s keep it simple.',7,13,4),
(1,'Leeds — Mature only','Prefer older.',10,20,5),
(1,'Glasgow — Friendly chats','Let’s talk.',1,2,6),
(1,'Edinburgh — Bookworm here','Love reading and deep chats.',3,7,7),
(1,'Cardiff — Fun and friendly','Let’s vibe.',5,11,8),
(1,'Bristol — Looking for someone real','Open to meeting.',7,13,9),
(1,'Sheffield — Casual chats','Let’s talk.',1,1,10),

(1,'Manchester — Looking for laughs','Sense of humour essential.',1,1,1),
(1,'London — Coffee date','Simple and relaxed.',7,13,2),
(1,'Birmingham — Friendly meet','Let’s chat.',5,11,3),
(1,'Liverpool — Open to new people','Seeing who’s around.',7,13,4),
(1,'Leeds — Discreet meets','Privacy important.',10,20,5),
(1,'Glasgow — Open-minded guy','Let’s talk.',1,2,6),
(1,'Edinburgh — Looking for connection','Friendly and chilled.',3,7,7),
(1,'Cardiff — No strings','Keeping it simple.',5,11,8),
(1,'Bristol — Friendly chats','Let’s meet.',7,13,9),
(1,'Sheffield — Open to meeting','Seeing who’s out there.',1,1,10),

(1,'Manchester — Looking for someone kind','Genuine people only.',1,1,1),
(1,'London — Quick meet?','In the area often.',7,13,2),
(1,'Birmingham — Looking for real vibes','Honest and chilled.',6,16,3),
(1,'Liverpool — Friendly guy','Let’s chat.',7,13,4),
(1,'Leeds — Mature chats only','Prefer older.',10,20,5),
(1,'Glasgow — Casual chats','Let’s talk.',1,2,6),
(1,'Edinburgh — Coffee and books','Love reading.',3,7,7),
(1,'Cardiff — Fun meets','Keeping it light.',5,11,8),
(1,'Bristol — Looking for good company','Friendly and open.',7,13,9),
(1,'Sheffield — Open to chats','Let’s talk.',1,1,10);

INSERT INTO messages (sender_id,receiver_id,ad_id,content) VALUES
(1,1,1,'Testing message system — looks good!'),
(1,1,2,'Another test message for ad 2.');

